---
# tasks file for k8s-install
- name: add a line hosts
  lineinfile:
     dest:  /etc/hosts
     line: '10.130.21.249    gcr.io'
  tags:
   - add_a_line

- name: unarchive tar.gz
  unarchive:
    src: http://10.130.21.95:5892/k8s186.tar.gz
    dest: /tmp
    remote_src: True

- name: install k8s rpm from a local file
  yum:
    name: 
    - ebtables
    - yum-utils
    - /tmp/432a40bb7dbe35e3c85cd926b015269b8de54809ad0f14ceecfd5a05acbe44a4-kubectl-1.8.6-0.x86_64.rpm
    - /tmp/919d83307b30c808a9bf17f08ab6d72612d08860a8923366e666ed072012f62a-kubeadm-1.8.6-0.x86_64.rpm
    - /tmp/f4011419193577161ae891a1b26986cae5f5e588941340db3abb771e2a677de7-kubelet-1.8.6-0.x86_64.rpm
    - /tmp/fe33057ffe95bfae65e2f269e1b05e99308853176e24a4d027bc082b471a07c0-kubernetes-cni-0.6.0-0.x86_64.rpm
    - /tmp/socat-1.7.3.2-2.el7.x86_64.rpm
    state: present
- name: shell cmd
  shell: |
    swapoff -a
    echo 'net.bridge.bridge-nf-call-ip6tables = 1' |tee -a /etc/sysctl.conf 
    echo 'net.bridge.bridge-nf-call-iptables = 1' |tee -a /etc/sysctl.conf 
    echo 'vm.swappiness=0' |tee -a /etc/sysctl.conf 
    sysctl -p
    echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
    echo 1 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
    IP=`hostname -I|awk '{print $1}'`
    hostname2=`hostname`
    echo "$IP  $hostname2" >> /etc/hosts
  args:
    executable: /bin/bash

- name: replace systemd in k8s-conf
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'systemd'
    replace: 'cgroupfs'
    backup: no

- name: daemon-reload
  command: systemctl daemon-reload

- name: restart service docker kubelet on centos, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    name: docker
    state: restarted
    enabled: True
  systemd: name=kubelet state=restarted enabled=yes
