---
- hosts: kvm12
  remote_user: dinghao
  sudo: yes
  vars:
    image_name: c7-200
    instance_name: '{{ name }}'
    instance_dir: /var/lib/libvirt/images
    tem_dir: /Users/dh/ansible-playbook/kvm/templates
    tem_file: "{{ tem_dir }}/set_ip_tem.sh.j2"
    file_name: /tmp/ifcfg-eth1

  tasks:
  - name: create the file set_ip.sh
    template: src={{ tem_file }} dest={{ file_name }}
    tags: file

